# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: chmod -R 777 ./
  displayName: 'Hopefully permission get passed into docker compose'

- script: docker-compose -f .devcontainer/docker-compose.yml run app bash -c "cd /workspace && shards install && crystal spec --junit_output /workspace/tmp"
  displayName: 'Build and Run the Specs'

- task: PublishTestResults@2
  condition: always() # Run this even if tests fail.
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: 'tmp/*.xml' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional